services:
  moderate:
    image: pilchh/moderate-api
    build:
      context: ./api
    pull_policy: always
    container_name: moderate-api
    environment:
      - IS_IN_CONTAINER=${IS_IN_CONTAINER}
      - PORT=${MOD_PORT}
      - MODERATED_IP=${MODERATED_IP}
      - SUBMIT_IP=${SUBMIT_IP}
      - MODERATED_PORT=${MODERATED_PORT}
      - SUBMIT_PORT=${SUBMIT_PORT}
      - MODERATE_QUEUE=${MODERATE_QUEUE}
      - SUBMIT_QUEUE=${SUBMIT_QUEUE}
    restart: unless-stopped
    ports:
      - 4100:3100
    volumes:
      - moderate:/var/lib/moderate/
  rmq-admin:
    image: rabbitmq:3-management
    container_name: rabbitmq-moderate
    ports:
      - 4101:5672
      - 4102:15672
    volumes:
      - rabbitmq-moderate:/var/lib/rabbitmq/
      - rabbitmq-moderate:/var/log/rabbitmq
volumes:
  rabbitmq-moderate:
  moderate:

networks:
  rabbitmq-moderate:
    driver: bridge
