services:
  moderate:
    image: pilchh/moderate-api
    build:
      context: ./api
    pull_policy: always
    container_name: moderate-api
    restart: unless-stopped
    ports:
      - 4100:3100
    volumes:
      - moderate:/var/lib/moderate/
  rmq-admin:
    image: rabbitmq:3-management
    container_name: rabbitmq-moderate
    ports:
      - 4101:5672
      - 4102:15672
    volumes:
      - rabbitmq-moderate:/var/lib/rabbitmq/
      - rabbitmq-moderate:/var/log/rabbitmq
volumes:
  rabbitmq-moderate:
  moderate:

networks:
  rabbitmq-moderate:
    driver: bridge
