services:
  jokes:
    image: pilchh/jokes-api
    build:
      context: ./api
    pull_policy: always
    container_name: jokes-api
    environment:
      - IS_IN_CONTAINER=${IS_IN_CONTAINER}
      - PORT=${JOKES_PORT}
      - MODERATED_IP=${MODERATED_IP}
      - MODERATED_PORT=${MODERATED_PORT}
      - MODERATED_QUEUE=${MODERATED_QUEUE}
    depends_on:
      - db
    ports:
      - 4000:3000
  etl:
    image: pilchh/jokes-etl
    build:
      context: ./etl
    pull_policy: always
    restart: unless-stopped
    container_name: jokes-etl
    environment:
      - IS_IN_CONTAINER=${IS_IN_CONTAINER}
      - PORT=${ETL_PORT}
      - MODERATED_IP=${MODERATED_IP}
      - MODERATED_PORT=${MODERATED_PORT}
      - MODERATED_QUEUE=${MODERATED_QUEUE}
    depends_on:
      - db
    ports:
      - 4001:3001
  db:
    image: mysql
    restart: no
    environment:
      - MYSQL_DATABASE=jokes_service
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '4002:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local