services:
  jokes:
    image: jokes-api
    build:
      context: ./api
    pull_policy: always
    container_name: jokes-api
    ports:
      - 4001:3001
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=jokes
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
