services:
  jokes:
    image: pilchh/jokes-api
    build:
      context: ./api
    pull_policy: always
    container_name: jokes-api
    ports:
      - 4000:3000
  etl:
    image: pilchh/jokes-etl
    build:
      context: ./etl
    pull_policy: always
    container_name: jokes-etl
    ports:
      - 4001:3001
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=jokes_service
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=pilchh
      - MYSQL_PASS=password
      - MYSQL_ROOT_HOST=%
    ports:
      - '4002:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
