services:
  moderate:
    image: pilchh/submit-api
    build:
      context: ./api
    pull_policy: always
    container_name: submit-api
    restart: unless-stopped
    ports:
      - 4200:3200
  rmq-admin:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 4201:5672
      - 4202:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
volumes:
  rabbitmq-submit:

networks:
  rabbitmq-submit:
    driver: bridge
