services:
  submit:
    image: pilchh/submit-api
    build:
      context: ./api
    pull_policy: always
    container_name: submit-api
    environment:
      - IS_IN_CONTAINER=${IS_IN_CONTAINER}
      - PORT=${SUBMIT_API_PORT}
      - SUBMIT_IP=${SUBMIT_IP}
      - SUBMIT_PORT=${SUBMIT_PORT}
      - SUBMIT_QUEUE=${SUBMIT_QUEUE}
    restart: unless-stopped
    ports:
      - 4200:3200
    volumes:
      - submit:/var/lib/submit/
  rmq-admin:
    image: rabbitmq:3-management
    container_name: rabbitmq-submit
    ports:
      - 4201:5672
      - 4202:15672
    volumes:
      - rabbitmq-submit:/var/lib/rabbitmq/
      - rabbitmq-submit:/var/log/rabbitmq
volumes:
  rabbitmq-submit:
  submit:
networks:
  rabbitmq-submit:
    driver: bridge
