services:
  kong:
    image: kong
    container_name: kong
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444
      - KONG_LOG_LEVEL=debug
    ports:
      - "80:8000" # API Endpoint HTTP
      - "8443:8443" # API Endpoint HTTPS
      - "127.0.0.1:8001:8001" # API Management HTTP
      - "127.0.0.1:8444:8444" # API Management HTTPS