services:
  kong:
    image: kong
    container_name: kong
    #command: "kong migrations bootstrap"
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
      - ./cert:/etc/secrets
      - ./kong.conf:/etc/kong/kong.conf
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_LOG_LEVEL=debug
      - KONG_ADMIN_SSL_CERT=/etc/secrets/azure.test+1.pem
      - KONG_ADMIN_SSL_CERT_KEY=/etc/secrets/azure.test+1-key.pem
    ports:
      - "80:8000" # API Endpoint HTTP
      - "443:8443" # API Endpoint HTTPS
      - "127.0.0.1:8001:8001" # API Management HTTP
      - "127.0.0.1:8444:8444" # API Management HTTPS